config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations' ,
   omniauth_callbacks: 'users/omniauth_callbacks'}
   
   resources :cards, only:[:index, :new, :create, :show] do
    collection do
      post 'create', to: 'cards#create'
      post 'pay', to: 'cards#pay'
     end
   end
 
   resources :purchases, only:[:index] do
     collection do
       get 'index', to: 'purchases#index'
       get 'cards', to: 'purchases#cards'
       post 'pay', to: 'purchases#pay'
       get 'done', to: 'purchases#done'
     end
   end
  
  devise_scope :user do 
    get 'users/sign_up/SNS' => 'users/registrations#SNS'
    get 'users/sign_up/address' => 'users/registrations#address'
    get 'users/sign_up/complete' => 'users/registrations#complete'
    get 'users/sign_up/index' => 'users/registrations#index'
    get 'users/sign_up/phone' => 'users/registrations#phone'
    get 'users/sign_up/step' => 'users/registrations#step'
    post 'users/sign_up/register' => 'users/registrations#register'
  end

  root 'products#index'

  resources :products, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only:[:create, :show]

    #product_idに紐づく商品表示に関するルート作成

    member do
      get 'show_my_product'
    end

    #Ajaxで動くカテゴリー選択アクションのルートを作成
    collection do
      get 'get_category_children_new', defaults: { format: 'json' }
      get 'get_category_grandchildren_new', defaults: { format: 'json' }
      get 'get_size_new', defaults: { format: 'json' }
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end

  end

  resources :users, only:[:index, :update] do
    collection do
      get 'email'
      get 'logout'
      post 'logout'
      get 'selling'
      get 'trading'
      get 'completed'
    end

    member do
      get 'profile'
    end
    resources :user_addresses, only:[:new, :create, :update]
    resources :delivery_addresses, only:[:new, :create, :update]

  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'users' => 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :sns_credentials
  has_one :user_address
  accepts_nested_attributes_for :user_address
  has_many :credit_cards
  has_many :products
  has_many :comments
  has_one :evaluation
  has_one :delivery_address
  has_one :credit_card

  validates :nickname,                presence: true, length: {maximum: 20}
  validates :email,                   presence: true, uniqueness: true
  validates :password,                presence: true, length: {minimum: 7, maximum: 128}
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{7,128}+\z/i }, on: :new_registration
  validates :last_name,               presence: true
  validates :first_name,              presence: true
  validates :last_name_kana,          presence: true
  validates :first_name_kana,         presence: true
  validates :birthday,                presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  
         def self.find_oauth(auth)
          uid = auth.uid
          provider = auth.provider
          snscredential = SnsCredential.where(uid: uid, provider: provider).first
          if snscredential.present?
            user = User.where(id: snscredential.user_id).first
            unless user
              # provider情報があったがユーザー情報がない場合
              user = User.create(
                nickname: auth.info.name,
                email:    auth.info.email,
                password: Devise.friendly_token[0, 20],
                )
            end
          else
            user = User.where(email: auth.info.email).first
            if user.present?
              # 同じemailでのユーザー情報があった場合
              SnsCredential.create(
                uid: uid,
                provider: provider,
                user_id: user.id
                )
            else
              # ユーザー情報がない場合
              user = User.create(
                nickname: auth.info.name,
                email:    auth.info.email,
                password: Devise.friendly_token[0, 20],
                )
              SnsCredential.create(
                uid: uid,
                provider: provider,
                user_id: user.id
                )
            end
          end
          return user
        end
      end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @user = User.find_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session[:nickname] = @user.nickname
      session[:email] = @user.email
      session[:password] = @user.password
      redirect_to users_sign_up_SNS_path
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout 'registrations_application'

  before_action :save_new_to_session, only: :phone
  before_action :save_phone_to_session, only: :address
  
  def new
    @user = User.new
    @user.build_user_address
  end

  def SNS
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
    )
    @user.build_user_address
  end

  def save_new_to_session
    session[:user_params] = user_params
    session[:user_address_attributes_after_new] = user_params[:user_address_attributes]
    @user = User.new(session[:user_params])
    @user.build_user_address(session[:user_address_attributes_after_new])
    render 'devise/registrations/new' unless @user.valid?(:new_registration)
  end

  def step
    params[:user][:birthday] = birthday_join
    session[:user_params] = user_params
    session[:user_address_attributes_after_new] = user_params[:user_address_attributes]
    @user = User.new(session[:user_params])
    @user.build_user_address(session[:user_address_attributes_after_new])
    render 'devise/registrations/SNS' unless @user.valid?
  end

  def index
  end

  def phone
    params[:user][:birthday] = birthday_join
    session[:user_params] = user_params
    @user = User.new
    @user.build_user_address
    # if verify_recaptcha
    # else
    #   flash.now[:recaptcha_error] = I18n.t('recaptcha.errors.verification_failed')
    #   return render action: :new
    # end
  end

  def save_phone_to_session
    session[:user_address_attributes_after_step2] = user_params[:user_address_attributes]
    session[:user_address_attributes_after_step2].merge!(session[:user_address_attributes_after_step1])
    @user = User.new
    @user.build_user_address(session[:user_address_attributes_after_step2])
    render 'devise/registrations/phone' unless session[:user_address_attributes_after_step2][:phone_number].present?
  end

  def address
    session[:user_address_attributes] = user_params[:user_address_attributes]
    @user = User.new(session[:user_params])
    @user.build_user_address
  end

  def complete
  end

  def register
      session[:user_address_attributes] = user_params[:user_address_attributes]
      @user = User.new(session[:user_params])
      @user.build_user_address(session[:user_address_attributes])
    if @user.save(context: :register)
       session[:id] = @user.id
       sns = SnsCredential.update(user_id:  @user.id)
       sign_in User.find(session[:id]) unless user_signed_in?
       redirect_to new_card_path
    else
       render 'devise/registrations/address'
    end
   end

   private
  def user_params
    params.require(:user).permit(
      :nickname,
      :email,
      :password,
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :birthday,
      user_address_attributes: [:id, :phone_number, :postal_code, :prefecture_id, :address_city, :address_street, :address_building]
      )
   end

    def birthday_join
    date = params[:user]

    if date["birthday(1i)"].empty? && date["birthday(2i)"].empty? && date["birthday(3i)"].empty?
      return
    end

    Date.new date["birthday(1i)"].to_i,date["birthday(2i)"].to_i,date["birthday(3i)"].to_i
    end
  end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'registrations_application'

  before_action :configure_sign_in_params, only: [:create]
  before_action :recaptcha,  only: [:create]
    
    def create
      super
      if verify_recaptcha(model: @user) && @user.save
      @user.save
      end
    end

  protected

    def configure_sign_in_params
      devise_parameter_sanitizer.permit(:sign_in,
        keys: [:email, :password,])
    end

    def recaptcha
    self.resource = resource_class.new sign_in_params
    resource.validate
    unless verify_recaptcha(model: resource)
      respond_with_navigational(resource) { render :new }
      end
    end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  end

  def profile
  end

  def update
    current_user.nickname = user_params[:nickname]
    current_user.self_introduction = user_params[:self_introduction]
    current_user.save(:validate => false)
    redirect_to profile_user_path(current_user)
  end

  def email
  end

  def selling
    @products = Product.where('seller_id = ? and current_status = ?', current_user.id, 0)
    @status = "出品中"
  end

  def trading
    @products = Product.where('seller_id = ? and current_status = ?', current_user.id, 1)
    @products.each do |product|
      if ( product.payment_status == 1 && product.sending_status == 0 )
        @status = "発送待ち" 
      else
        @status = "受け取り評価待ち"
      end
    end
  end
  
  def completed
    @products = Product.where('seller_id = ? and current_status = ?', current_user.id, 2)
    @status = "売却済み"
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :self_introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_items_mine.html.haml
%ul.mypage-item__list
  - products.each do |product|
    = link_to show_my_product_product_path(product) do
      %li.mypage-item__list__link
        %figure
          =image_tag product.product_images.first.image.url, alt: '画像', class: "mypage-item__icon-mercari", alt:"mypage-item__icon-mercari"
        .mypage-item__body
          .mypage-item__text
            = product.name
          .mypage-item__bottom
            %span.listing-item-count
              = fa_icon "heart-o", class: "icon"
              = product.like
            %span.listing-item-count
              = fa_icon "comment-o", class: "icon"
              = product.comments.count
            .mypage-item__bottom--status
              = status               

        %i.fa.fa-chevron-right

app/views/users/_side_bar.html.haml
.side
  .side--list
    .side--list--item
      = link_to users_path do
        マイページ
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to "" do
        お知らせ
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to "" do
        やることリスト
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to "" do
        いいね！一覧
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to new_product_path do
        出品する
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to selling_users_path do
        出品した商品 - 出品中
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to trading_users_path do
        出品した商品 - 取引中
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to completed_users_path do
        出品した商品 - 売却済み
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to "" do
        購入した商品 - 取引中
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to "" do
        出品した商品 - 過去の取引
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to "" do
        ニュース一覧
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to "" do
        評価一覧
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to "" do
        ガイド
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to "" do
        お問い合わせ
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--head
      メルペイ

    .side--list--item
      = link_to "" do
        売上・振込申請
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to "" do
        ポイント
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--head
      設定

    .side--list--item
      = link_to profile_user_path(current_user) do
        プロフィール
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to new_user_delivery_address_path(current_user) do
        発送元・お届け先住所変更
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to pay_cards_path do
        支払い方法
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to email_users_path(current_user) do
        メール/パスワード
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to new_user_user_address_path(current_user) do
        本人情報
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to "" do
        電話番号の確認
        = fa_icon "angle-right" , class: "side--list--icon"

    .side--list--item
      = link_to "ログアウト", logout_users_path , class: "logout"
      = fa_icon "angle-right" , class: "side--list--icon"

app/views/users/completed.html.haml
- breadcrumb :completed
= render "layouts/breadcrumbs"
.container-mypage
  .container-mypage__content
    .container-mypage__content--head
      出品した商品
    .container-mypage__content--body
      %ul.mypage-tabs

        = link_to selling_users_path do
          %li.mypage-tabs__left
            .mypage-tabs__left__text
              %h3 出品中

        = link_to trading_users_path do
          %li.mypage-tabs__middle
            .mypage-tabs__middle__text
              %h3 取引中

        %li.mypage-tabs__right.border-red
          .mypage-tabs__right__text
            %h3 売却済み

      - if @products == []
        .tab-content.not-active
          %li.mypage-tabs__text 売却済みの商品はありません
      - else
        = render 'items_mine', products: @products, status: @status

  .side
    = render  "users/side_bar", user: current_user

app/views/users/edit.html.haml
-# headerは切り取ってあります_header.html.hamlにあります

.wrapper-profile
  .container.clearfix
    .container__right
      .container__right--title
        %h2 プロフィール
      = form_for @user, class: "container__right__form" do |f|
        .container__right__form--name
          = image_tag "top_page/icon-avater.png", size: "60x60"
          = f.text_field :nickname, class: "nickname", placeholder: "例）AYA☆セール中"
        .container__right__form--content
          = f.text_area :self_introduction, class: "text", placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"
          %button.container__right__form--btn{type: "submit"} 変更する
      
    .container__left
      = render partial: "side_bar"

-# footer(aside入り)は切り取ってあります_footer.html.hamlにあります

app/views/users/email.html.haml
- breadcrumb :email
= render "layouts/breadcrumbs"

%main.l-container.clearfix
  .l-content
    %section.l-chapter-container
      %h2.l-chapter-head メール/パスワード
      %form.l-single-inner{:action => "", :method => "POST", :novalidate => "novalidate"}
        %input{:name => "__csrf_value", :type => "hidden", :value => ""}
        .l-single-content
          = form_for current_user, html: { class: "" } do |f|
            .form-group
              %label{:for => "email"} メールアドレス
              %input.input-default{:name => "email", :placeholder => "PC・携帯どちらでも可", :type => "email", :value => current_user.email }
              %p.form-info-text メールアドレスを変更すると確認メールが送信されます。メール内のURLをクリックすると変更完了です。
            .form-group
              %label{:for => "current_password"} 現在のパスワード
              %input.input-default{:name => "current_password", :type => "password"}
              %label{:for => "password"} 新しいパスワード
              %input.input-default{:name => "password", :placeholder => "7文字以上の半角英数字", :type => "password"}
              %p.form-info-text ※ 英字と数字の両方を含めて設定してください
              %label.password-form{:for => "password_confirmation"} 新しいパスワード確認
              %input.input-default{:name => "password_confirmation", :placeholder => "新しいパスワードを再入力", :type => "password"}
              %p.form-info-text 
            %button.btn-default.btn-red{:type => "submit"} 変更する

  .side
    = render "side_bar", user: current_user

app/views/users/index.html.haml
- breadcrumb :mypage
= render "layouts/breadcrumbs"
.container-mypage
  .container-mypage__content
    .container-mypage__usericon
      = link_to "" do
        %figure
          =image_tag "top_page/icon-avater.png", size: '50x50', class: "avater", alt:"avater"
        .user ユーザー名
        .user--number
          .user--number__evaluation
            評価 0
          .user--number__exhibits
            出品数 0

    .container-mypage__news
      %ul.mypage-tabs
        %li.mypage-tabs__left
          .mypage-tabs__news
            お知らせ

        %li.mypage-tabs__right
          .mypage-tabs__notice
            やることリスト

      .tab-content__left
        %ul.mypage-item__list
          %li
            .mypage-item__link
              %figure
                =image_tag "mypage/mypage-icon-mercari.png", size: '50x50', class: "mypage-item__icon-mercari", alt:"mypage-item__icon-mercari"
              .mypage-item__body
                .mypage-item__text 
                  メッセージ「         」
                %time
                  %i.fa.fa-clock
                  %span 0 分前
              %i.fa.fa-chevron-right
          %li
            .mypage-item__link
              %figure
                =image_tag "mypage/mypage-icon-mercari.png", size: '50x50', class: "mypage-item__icon-mercari", alt:"mypage-item__icon-mercari"
              .mypage-item__body
                .mypage-item__text 
                  メッセージ「         」
                %time
                  %i.fa.fa-clock
                  %span 0 分前
              %i.fa.fa-chevron-right
          %li
            .mypage-item__link
              %figure
                =image_tag "mypage/mypage-icon-mercari.png", size: '50x50', class: "mypage-item__icon-mercari", alt:"mypage-item__icon-mercari"
              .mypage-item__body
                .mypage-item__text 
                  メッセージ「         」
                %time
                  %i.fa.fa-clock
                  %span 0 分前
              %i.fa.fa-chevron-right
          %li
            .mypage-item__link
              %figure
                =image_tag "mypage/mypage-icon-mercari.png", size: '50x50', class: "mypage-item__icon-mercari", alt:"mypage-item__icon-mercari"
              .mypage-item__body
                .mypage-item__text 
                  メッセージ「         」
                %time
                  %i.fa.fa-clock
                  %span 0 分前
              %i.fa.fa-chevron-right

          %li.mypage-item--all
            .mypage-item--all__text
              一覧を見る
      .tab-content__right.hide
        %li.mypage-tabs__right-text 現在、やることリストはありません

    .container-mypage-buy
      .mypage-buy--head 
        購入した商品
      %ul.mypage-buy--tabs
        %li.mypage-buy--tabs__trading-now
          取引中
        %li.mypage-buy--tabs__trading-old
          過去の取引
      .mypage-buy--content
        %ul.mypage-buy--content__now--list
          %li.mypage-buy--content__now--text 
            取引中の商品がありません
        %ul.mypage-buy--content__old--list.hide
          %li.mypage-buy--content__old--text
            過去に取引した商品がありません


  .side
    = render "side_bar", user: current_user

.camera-button
  .camera-button__text
    出品
  -#↓↓あとで出品ページのリンクに変える
  = link_to root_path do  
    = fa_icon "camera",class: "camera-button__icon"

app/views/users/logout.html.haml
.wrapper-logout
  .container
    .container__right
      .container__right--logout
        .container__right--logout-button
          = button_to destroy_user_session_path, method: :delete ,class: "logout__button" do
            ログアウト  

      
    .container__left
      = render partial: "side_bar"

app/views/users/profile.html.haml
-# headerは切り取ってあります_header.html.hamlにあります
- breadcrumb :profile
= render "layouts/breadcrumbs"

.wrapper-profile
  .container
    .container__right
      .container__right--title
        %h2 プロフィール
      = form_for current_user, html: { class: "container__right__form" } do |f|
        .container__right__form--name
          = image_tag "top_page/icon-avater.png", size: "60x60"
          = f.text_field :nickname, value: current_user.nickname, class: "nickname", placeholder: "例）AYA☆セール中"
        .container__right__form--content
          = f.text_area :self_introduction, class: "text", placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"
          %button.container__right__form--btn{type: "submit"} 変更する
      
    .container__left
      = render "side_bar", user: current_user

-# footer(aside入り)は切り取ってあります_footer.html.hamlにあります

app/views/users/selling.html.haml
- breadcrumb :selling
= render "layouts/breadcrumbs"

.container-mypage
  .container-mypage__content
    .container-mypage__content--head
      出品した商品
    .container-mypage__content--body
      %ul.mypage-tabs
        %li.mypage-tabs__left.border-red
          .mypage-tabs__left__text
            %h3 出品中

        = link_to trading_users_path do
          %li.mypage-tabs__middle
            .mypage-tabs__middle__text
              %h3 取引中

        = link_to completed_users_path do
          %li.mypage-tabs__right
            .mypage-tabs__right__text
              %h3 売却済み

      
      - if @products == []
        .tab-content
          %li.mypage-tabs__text 出品中の商品はありません
      - else
        = render 'items_mine', products: @products, status: @status

  .side
    = render  "users/side_bar", user: current_user

app/views/users/show.html.haml
-# headerは切り取ってあります_header.html.hamlにあります

.wrapper-identification
  .container
    .container__right
      .container__right--title
        %h2 本人情報の登録
      = form_for @user, html: {class: "container__right__form"} do |f|
        .container__right__form--text
          %p お客さまの本人情報をご登録ください。
          %p 登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        .container__right__form--text--right
          = link_to "" do
            = fa_icon "angle-right" , class: "icon"
            %p 本人確認書類のアップロードについて
        
        -# ↓実際のデータはUserモデルより取得
        .container__right__form--group
          %label お名前
          %p メルカリ太郎

        .container__right__form--group
          %label お名前カナ
          %p メルカリタロウ

        .container__right__form--group
          %label 生年月日
          %p 2019/01/01

        .container__right__form--group
          %label 郵便番号
          %span.arbitrary  任意
          = f.text_field :postal_code, class: "input", placeholder: "例）1234567"
       
        -# ↓f.collection_selectを使用する予定
        .container__right__form--group
          %label 都道府県
          %span.arbitrary  任意
          = f.text_field :prefecture, class: "input", placeholder: "東京都"

        .container__right__form--group
          %label 市区町村
          %span.arbitrary  任意
          = f.text_field :postal_code, class: "input", placeholder: "例）横浜市緑区"

        .container__right__form--group
          %label 番地
          %span.arbitrary  任意
          = f.text_field :postal_code, class: "input", placeholder: "例）青山1-1-1"

        .container__right__form--group
          %label 建物名
          %span.arbitrary  任意
          = f.text_field :postal_code, class: "input", placeholder: "例）柳ビル101"

        %button.container__right__form--btn{type: "submit"} 変更する


      
    .container__left
      = render partial: "side_bar"

-# footer(aside入り)は切り取ってあります_footer.html.hamlにあります

app/views/users/trading.html.haml
- breadcrumb :trading
= render "layouts/breadcrumbs"
.container-mypage
  .container-mypage__content
    .container-mypage__content--head
      出品した商品
    .container-mypage__content--body
      %ul.mypage-tabs

        = link_to selling_users_path do
          %li.mypage-tabs__left
            .mypage-tabs__left__text
              %h3 出品中

        %li.mypage-tabs__middle.border-red
          .mypage-tabs__middle__text
            %h3 取引中

        = link_to completed_users_path do
          %li.mypage-tabs__right
            .mypage-tabs__right__text
              %h3 売却済み

      - if @products == []
        .tab-content.not-active
          %li.mypage-tabs__text 取引中の商品はありません
      - else
        = render 'items_mine', products: @products, status: @status

  .side
    = render  "users/side_bar", user: current_user