config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations' ,
   omniauth_callbacks: 'users/omniauth_callbacks'}
   
   resources :cards, only:[:index, :new, :create, :show] do
    collection do
      post 'create', to: 'cards#create'
      post 'pay', to: 'cards#pay'
     end
   end
 
   resources :purchases, only:[:index] do
     collection do
       get 'index', to: 'purchases#index'
       get 'cards', to: 'purchases#cards'
       post 'pay', to: 'purchases#pay'
       get 'done', to: 'purchases#done'
     end
   end
  
  devise_scope :user do 
    get 'users/sign_up/SNS' => 'users/registrations#SNS'
    get 'users/sign_up/address' => 'users/registrations#address'
    get 'users/sign_up/complete' => 'users/registrations#complete'
    get 'users/sign_up/index' => 'users/registrations#index'
    get 'users/sign_up/phone' => 'users/registrations#phone'
    get 'users/sign_up/step' => 'users/registrations#step'
    post 'users/sign_up/register' => 'users/registrations#register'
  end

  root 'products#index'

  resources :products, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only:[:create, :show]

    #product_idに紐づく商品表示に関するルート作成

    member do
      get 'show_my_product'
    end

    #Ajaxで動くカテゴリー選択アクションのルートを作成
    collection do
      get 'get_category_children_new', defaults: { format: 'json' }
      get 'get_category_grandchildren_new', defaults: { format: 'json' }
      get 'get_size_new', defaults: { format: 'json' }
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end

  end

  resources :users, only:[:index, :update] do
    collection do
      get 'email'
      get 'logout'
      post 'logout'
      get 'selling'
      get 'trading'
      get 'completed'
    end

    member do
      get 'profile'
    end
    resources :user_addresses, only:[:new, :create, :update]
    resources :delivery_addresses, only:[:new, :create, :update]

  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'users' => 'users#index'
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
    require 'payjp'
    layout 'others_application'

    def index
     @useraddress = UserAddress.where(user_id: current_user.id)
     @product = Product.find(params[:product])
     card = CreditCard.where(user_id: current_user.id).first
      if card.blank?
       redirect_to new_card_path
        else
        Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
        customer = Payjp::Customer.retrieve(card.customer_id)
        @default_card_information = customer.cards.retrieve(card.card_id)
        @card_brand = @default_card_information.brand    
        case @card_brand
         when "Visa"
         @card_src = "visa.svg"
         when "JCB"
         @card_src = "jcb.svg"
         when "MasterCard"
         @card_src = "master-card.svg"
         when "American Express"
         @card_src = "american_express.svg"
         when "Diners Club"
         @card_src = "dinersclub.svg"
         when "Discover"
         @card_src = "discover.svg"
        end
      end
    end
  
  def cards
    @product = Product.find(params[:product])
    card = CreditCard.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
      @card_brand = @default_card_information.brand    
      case @card_brand
      when "Visa"
        @card_src = "visa.svg"
      when "JCB"
        @card_src = "jcb.svg"
      when "MasterCard"
        @card_src = "master-card.svg"
      when "American Express"
        @card_src = "american_express.svg"
      when "Diners Club"
        @card_src = "dinersclub.svg"
      when "Discover"
        @card_src = "discover.svg"
      end
    end
  end

  def pay
    card = CreditCard.where(user_id: current_user.id).first
    @product = Product.find(params[:product])
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp::Charge.create(
    :amount => @product.price,
    :customer => card.customer_id, #顧客ID
    :currency => 'jpy', #日本円
    )
    if @product.update(buyer_id: current_user.id)
      redirect_to done_purchases_path(product: @product)
    else
      redirect_to done_purchases_path(product: @product)
    end
  end
  
  def done
    @product = Product.find(params[:product])
    @useraddress = UserAddress.where(user_id: current_user.id)
  end

end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/cards.html.haml
.purchase
 .purchase_show
  .purchase_show_view
   %h2.purchase_view_title 支払い方法
 .purchase_option
  .purchase_option_creditcards
   .purchase_option_creditcards_info
    %label クレジットカード一覧
    %br
    = image_tag "card/#{@card_src}",size: '50x30', alt: @card_brand, id: "card_image"
    %br
    = "**** **** **** " + @default_card_information.last4
    %br
    - @default_card_information.brand
    - exp_month = @default_card_information.exp_month.to_s
    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    = exp_month + " / " + exp_year

.purchase_next
 .purchase_next_btn
  %a{ href: purchases_path(product: @product), class: "purchase_next_btn"}
   %button 次へ進む

app/views/purchases/done.html.haml
.purchase
 .purchase_notification
  .purchase_notification_sending
   %i.far.fa-clock 発送をお待ち下さい。
   %p.notice 出品者からの発送通知をお待ちください。
   
  .purchase_notification_view
   %h2.purchase_view_title 購入が完了しました
  
  .purchase_notification_product
   = image_tag( @product.product_images[0].image, class: "product-image", size: '200x200' )
   .purchase_notification_product_title
    = @product.name

  .purchase_notification_price
   %li.yen
    = "¥ #{@product.price}"
   %li 送料込み
  -#  = @product.shipping_charge

  .purchase_notification_form
   .purchase_notification_form_base
    - @useraddress.each do |useraddress|
     %label 配送先
     .purchase-postal
      〒
      = useraddress.postal_code
      %br
      = useraddress.prefecture.name + useraddress.address_city + useraddress.address_street + useraddress.address_building
      %br
      = current_user.nickname

  .purchase_notification_back
   = link_to "商品へ戻る", product_path(@product)

app/views/purchases/index.html.haml
.purchase
 .purchase_container
  .purchase_container_view
   %h2.purchase_view_title 購入内容の確認

 = form_tag(product: @product, action: :pay, method: :post) do
  .purchase_container_form
   .purchase_container_form_base
    .purchase_container_form_base_product
     = image_tag( @product.product_images[0].image, class: "product-image", size: '60x60')
    .purchase_container_form_base_title
     = @product.name

   .purchase_container_form_base
    .purchase_container_form_base_price
     %li.yen
      = "¥ #{@product.price}"
     %li 送料込み
    -#  = @product.shiiping_charge

    .purchase_container_form_base_point
     ポイントはありません
    .purchase_container_form_base_pay
     %li 支払い金額
     %li
     = "¥ #{@product.price}"

   .purchase_container_form_base
    %button{type: "submit",class: "purchase_btn"}購入する
 
  .purchase_container_address
   .purchase_container_address_profile
    - @useraddress.each do |useraddress|
     %label 配送先
     .purchase-address
      〒
      = useraddress.postal_code
      %br
      = useraddress.prefecture.name + useraddress.address_city + useraddress.address_street + useraddress.address_building
      %br
      = current_user.nickname
     .purchase-link
      = link_to "変更する ＞",class: "change-profile"

  .purchase_container_creditcard
   .purchase_container_creditcard_number
    %label 支払い方法
    %br
    .purchase_info
     = "**** **** **** " + @default_card_information.last4
     %br
     - exp_month = @default_card_information.exp_month.to_s
     - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
     = exp_month + " / " + exp_year
     %br
     = image_tag "card/#{@card_src}",size: '50x30', alt: @card_brand, id: "card_image"
     .purchase-link
      = link_to "変更する ＞", cards_purchases_path(product: @product),class: "change-creditcard"