config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations' ,
   omniauth_callbacks: 'users/omniauth_callbacks'}
   
   resources :cards, only:[:index, :new, :create, :show] do
    collection do
      post 'create', to: 'cards#create'
      post 'pay', to: 'cards#pay'
     end
   end
 
   resources :purchases, only:[:index] do
     collection do
       get 'index', to: 'purchases#index'
       get 'cards', to: 'purchases#cards'
       post 'pay', to: 'purchases#pay'
       get 'done', to: 'purchases#done'
     end
   end
  
  devise_scope :user do 
    get 'users/sign_up/SNS' => 'users/registrations#SNS'
    get 'users/sign_up/address' => 'users/registrations#address'
    get 'users/sign_up/complete' => 'users/registrations#complete'
    get 'users/sign_up/index' => 'users/registrations#index'
    get 'users/sign_up/phone' => 'users/registrations#phone'
    get 'users/sign_up/step' => 'users/registrations#step'
    post 'users/sign_up/register' => 'users/registrations#register'
  end

  root 'products#index'

  resources :products, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only:[:create, :show]

    #product_idに紐づく商品表示に関するルート作成

    member do
      get 'show_my_product'
    end

    #Ajaxで動くカテゴリー選択アクションのルートを作成
    collection do
      get 'get_category_children_new', defaults: { format: 'json' }
      get 'get_category_grandchildren_new', defaults: { format: 'json' }
      get 'get_size_new', defaults: { format: 'json' }
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end

  end

  resources :users, only:[:index, :update] do
    collection do
      get 'email'
      get 'logout'
      post 'logout'
      get 'selling'
      get 'trading'
      get 'completed'
    end

    member do
      get 'profile'
    end
    resources :user_addresses, only:[:new, :create, :update]
    resources :delivery_addresses, only:[:new, :create, :update]

  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'users' => 'users#index'
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  layout 'registrations_application', only: [:new]

  def new
    card = CreditCard.where(user_id: current_user.id)
    redirect_to root_path if card.exists?
  end

  def create
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save!
        redirect_to users_sign_up_complete_path
      else
        redirect_to new_card_path
      end
    end
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = CreditCard.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
      @card_brand = @default_card_information.brand    
      case @card_brand
      when "Visa"
        @card_src = "visa.svg"
      when "JCB"
        @card_src = "jcb.svg"
      when "MasterCard"
        @card_src = "master-card.svg"
      when "American Express"
        @card_src = "american_express.svg"
      when "Diners Club"
        @card_src = "dinersclub.svg"
      when "Discover"
        @card_src = "discover.svg"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = CreditCard.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

end

app/views/cards/_show.html.haml
.purchase
 .purchase_show
  .purchase_show_view
   %h2.purchase_view_title 支払い方法
 .purchase_option
  .purchase_option_creditcards
   .purchase_option_creditcards_info
    %label クレジットカード一覧
    %br
    = image_tag "card/#{@card_src}",size: '50x30', alt: @card_brand, id: "card_image"
    %br
    = "**** **** **** " + @default_card_information.last4
    %br
    - @default_card_information.brand
    - exp_month = @default_card_information.exp_month.to_s
    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    = exp_month + " / " + exp_year

app/views/cards/create.html.haml
.wrapper-card
  .container
    .container__right
      .container__right--title
        %h2 クレジットカード情報入力
      = form_tag(method: :post, id: 'card-form', name: "inputForm" ) do
        .container__right--content
          .container__right--content--main
            .form
              %label カード番号
              %span.form--require 必須
              = text_field_tag "number", "", class: "card-input", placeholder: "半角数字のみ", maxlength: "16", id: "card_number"

            .cardlist
              = image_tag "card/visa.svg", size: "49x20", class: "card-icon"
              = image_tag "card/master-card.svg", size: "34x20", class: "card-icon"
              = image_tag "card/saison-card.svg", size: "30x20", class: "card-icon"
              = image_tag "card/jcb.svg", size: "32x20", class: "card-icon"
              = image_tag "card/american_express.svg", size: "21x20", class: "card-icon"
              = image_tag "card/dinersclub.svg", size: "32x20", class: "card-icon"
              = image_tag "card/discover.svg", size: "32x20", class: "card-icon"
              
            .form.margin-top.height-middle
              %label 有効期限
              %span.form--require 必須
              %br
              .form__half
                %select#exp_month{name: "exp_month", type: "text"}
                  %option{value: ""} --
                  %option{value: "1"} 01
                  %option{value: "2"} 02
                  %option{value: "3"} 03
                  %option{value: "4"} 04
                  %option{value: "5"} 05
                  %option{value: "6"} 06
                  %option{value: "7"} 07
                  %option{value: "8"} 08
                  %option{value: "9"} 09
                  %option{value: "10"} 10
                  %option{value: "11"} 11
                  %option{value: "12"} 12
                %span 月
            
              .form__half
                %select#exp_year{name: "exp_year", type: "text"}
                  %option{value: ""} --
                  %option{value: "2019"}19
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                %span 年
                %br
              
            .form.margin-top
              %label セキュリティコード
              %span.form--require 必須
              = text_field_tag "cvc", "", class: "card-input", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
              -# %i.fa.fa-question-circle
              .form--text
                = fa_icon "question-circle" , class: "seq-icon"
                カード裏面の番号とは？
            #card_token
            %button.margin-top.red{type: "submit", id: "token_submit"} 追加する

    .container__left
      = render  "users/side_bar", user: current_user

-# footer(aside入り)は切り取ってあります_footer.html.hamlにあります

app/views/cards/index.html.haml
-# headerは切り取ってあります_header.html.hamlにあります
- breadcrumb :payment
= render "layouts/breadcrumbs"
.wrapper-card
  .container
    .container__right
      .container__right--title
        %h2 支払い方法
      .container__right--content
        .container__right--content--top
          %h3 クレジットカード一覧
        .container__right--content--bottom
          .container__right--content--bottom--add-card
            = link_to cards_path, method: :POST do
              = fa_icon "angle-right" , class: "icon"
              クレジットカードを追加する

        .container__right--content--text--right
          = link_to "" do
            = fa_icon "angle-right" , class: "icon"
            %p 支払い方法について
      
    .container__left
      = render  "users/side_bar", user: current_user

-# footer(aside入り)は切り取ってあります_footer.html.hamlにあります

app/views/cards/new.html.haml
.register-header
 .register-header_content
  %h1
   %a
    = image_tag "top_page/header-mercari.svg", size: '180x50', alt:"mercari"  
  .header-bar
   %ol
    %li
     会員情報
     .border-radius_red
     .header-border_red

    %li
     電話番号認証
     .border-radius_red
     .header-border_red

    %li 
     お届け先住所入力
     .border-radius_red
     .header-border_red

    %li.info  
     支払い方法
     .border-radius_red
     .header-border

    %li 
     完了
     .border-radius

.register
 .register_container
  .register_container_view
   %h2.register-view_title 支払い方法
  
 .new-credit
  = form_tag(cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
   .new-credit_form
    %label カード番号
    %span.form-require 必須
    %br
     = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
   
   .new-credit_form
    %label 有効期限
    %span.form-require 必須
    %br
    %select#exp_month{name: "exp_month", type: "text"}
     %option{value: ""} --
     %option{value: "1"}01
     %option{value: "2"}02
     %option{value: "3"}03
     %option{value: "4"}04
     %option{value: "5"}05
     %option{value: "6"}06
     %option{value: "7"}07
     %option{value: "8"}08
     %option{value: "9"}09
     %option{value: "10"}10
     %option{value: "11"}11
     %option{value: "12"}12
    %span 月

    %select#exp_year{name: "exp_year", type: "text"}
     %option{value: ""} --
     %option{value: "2019"}19
     %option{value: "2020"}20
     %option{value: "2021"}21
     %option{value: "2022"}22
     %option{value: "2023"}23
     %option{value: "2024"}24
     %option{value: "2025"}25
     %option{value: "2026"}26
     %option{value: "2027"}27
     %option{value: "2028"}28
     %option{value: "2029"}29
    %span 年
    %br
   
   .new-credit_form
    %label セキュリティコード
    %span.form-require 必須
    = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
    %p 
     %i.fa.fa-question-circle 
      カード裏面の番号とは？

   .new-credit_form 
    #card_token
     = submit_tag "次へ進む", id: "token_submit"

app/views/cards/show.html.haml
.purchase
 .purchase_show
  .purchase_show_view
   %h2.purchase_view_title 支払い方法
 .purchase_option
  .purchase_option_creditcards
   .purchase_option_creditcards_info
    %label クレジットカード一覧
    %br
    = image_tag "card/#{@card_src}",size: '50x30', alt: @card_brand, id: "card_image"
    %br
    = "**** **** **** " + @default_card_information.last4
    %br
    - @default_card_information.brand
    - exp_month = @default_card_information.exp_month.to_s
    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    = exp_month + " / " + exp_year