config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations' ,
   omniauth_callbacks: 'users/omniauth_callbacks'}
   
   resources :cards, only:[:index, :new, :create, :show] do
    collection do
      post 'create', to: 'cards#create'
      post 'pay', to: 'cards#pay'
     end
   end
 
   resources :purchases, only:[:index] do
     collection do
       get 'index', to: 'purchases#index'
       get 'cards', to: 'purchases#cards'
       post 'pay', to: 'purchases#pay'
       get 'done', to: 'purchases#done'
     end
   end
  
  devise_scope :user do 
    get 'users/sign_up/SNS' => 'users/registrations#SNS'
    get 'users/sign_up/address' => 'users/registrations#address'
    get 'users/sign_up/complete' => 'users/registrations#complete'
    get 'users/sign_up/index' => 'users/registrations#index'
    get 'users/sign_up/phone' => 'users/registrations#phone'
    get 'users/sign_up/step' => 'users/registrations#step'
    post 'users/sign_up/register' => 'users/registrations#register'
  end

  root 'products#index'

  resources :products, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only:[:create, :show]

    #product_idに紐づく商品表示に関するルート作成

    member do
      get 'show_my_product'
    end

    #Ajaxで動くカテゴリー選択アクションのルートを作成
    collection do
      get 'get_category_children_new', defaults: { format: 'json' }
      get 'get_category_grandchildren_new', defaults: { format: 'json' }
      get 'get_size_new', defaults: { format: 'json' }
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end

  end

  resources :users, only:[:index, :update] do
    collection do
      get 'email'
      get 'logout'
      post 'logout'
      get 'selling'
      get 'trading'
      get 'completed'
    end

    member do
      get 'profile'
    end
    resources :user_addresses, only:[:new, :create, :update]
    resources :delivery_addresses, only:[:new, :create, :update]

  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'users' => 'users#index'
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images, allow_destroy: true


  belongs_to :category
  has_many :comments
  has_one :evaluation
  belongs_to :brand, optional: true
  belongs_to :size, optional: true
  belongs_to :seller, class_name: "User" ,optional: true
  belongs_to :buyer, class_name: "User",optional: true

  validates :name, length: { in: 1..40}, presence: true
  validates :description, length: { in: 1..1000}, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 300, less_than: 9999999}

  # 商品の状態   0:新品、未使用 1: 未使用に近い 2:目立った傷や汚れなし 3:やや傷や汚れあり 4:やや傷や汚れあり 5:全体的に状態が悪い
  enum condition: { unused: 0, almost_new: 1, normal: 2, a_little_dirty: 3, dirty: 4, bad: 5 }
  # 配送料の負担   0:送料込み(出品者負担) 1: 着払い(購入者負担)
  enum shipping_charge: { sender_expense: 0, receiver_expense: 1 }
  # 配送の方法   0:未定 1: クロネコヤマト 2:ゆうパック 3:ゆうメール
  enum shipping_method: { unknown: 0, kuroneko: 1, yupack: 2, yumail: 3 }
  # 配送までの日数   0:1〜2日で発送 1: 2〜3日で発送 2:4〜7日で発送
  enum shipping_days: { immediately: 0, a_few_days: 1, four_to_seven_days: 2 }
  # 商品のステータス   0:出品中 1: 取引中 2:売却済み
  enum current_status: { selling: 0, trading: 1, completed: 2 }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_category, only: [:index, :edit, :update]
  before_action :set_brand, only: :index
  before_action :set_product_info, only:[:show, :show_my_product, :edit]

  def index
  end

  def new
    @product = Product.new
    @product.product_images.new
    @category_parent_array = ["---"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name  #親カテゴリー
    end

  end

  def create
    @product = Product.new(product_params)
    if @product.save
      # 商品の画像を保存
      if params.has_key?(:product_images)
        params[:product_images][:image].each do |image|
          @product_images = @product.product_images.update(image: image, product_id: @product.id)
        end
      end
      # 商品のブランドを保存
      if params.require(:product)[:brand_id] != nil
        selected_brand = Brand.where(name: params.require(:product)[:brand_id])
        new_brand_id = selected_brand.ids
        @product.update(brand_id: new_brand_id[0])
      end
      redirect_to root_path
    else
      redirect_to new_product_path
    end
  end

  def destroy
    @product.destroy
    redirect_to root_path
  end

  def show
  end

  def show_my_product
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
     # 商品のサイズとブランド以外を更新
    @product.update(product_params)

    # 商品の画像を更新
    if params.has_key?(:product_images)
      params[:product_images][:image].each do |image|
        @product_images = @product.product_images.create(image: image, product_id: @product.id)
      end

    end
    # 商品のサイズを更新
    if params.require(:product)[:size_id] != nil
      selected_size = Size.where(name: params[:size_id])
      new_size_id = selected_size.ids
      @product.update(size_id: new_size_id[0])
    end

    # 商品のブランドを更新
    if params.require(:product)[:brand_id] != nil
      selected_brand = Brand.where(name: params.require(:product)[:brand_id])
      new_brand_id = selected_brand.ids
      @product.update(brand_id: new_brand_id[0])
    end
    redirect_to show_my_product_product_path
  end

  def set_product_info
    @product = Product.find(params[:id])
    @product_images = @product.product_images
    @ship_from = Prefecture.find(@product.ship_from).name
    @comment = Comment.new
    @comments = @product.comments.includes(:user)
    @user = @product.seller
    @products_related_user = Product.where(seller_id: @user.id).limit(6)
    @products_related_category = Product.where(category_id: @product.category_id).limit(6)
    @sizelist = Size.all
    @price = @product.price
    @price_fee = ( @price * 0.1 ).round
    @price_profit = @price - @price_fee

    # 商品の状態   0:新品、未使用 1: 未使用に近い 2:目立った傷や汚れなし 3:やや傷や汚れあり 4:やや傷や汚れあり 5:全体的に状態が悪い
    @condition = @product.condition_i18n
    # 配送料の負担   0:送料込み(出品者負担) 1: 着払い(購入者負担)
    @shipping_charge = @product.shipping_charge_i18n
    # 配送の方法   0:未定 1: クロネコヤマト 2:ゆうパック 3:ゆうメール
    @shipping_method = @product.shipping_method_i18n
    # 配送までの日数   0:1〜2日で発送 1: 2〜3日で発送 2:4〜7日で発送
    @shipping_days = @product.shipping_days_i18n

    # 商品情報編集ページ(edit)のセレクトボックス初期値設定
    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name  #親カテゴリー
    end

    @category_children_default = []
    @product.category.root.children.each do |child|
      @category_children_default << child  #表示している商品に紐付く子カテゴリー
    end
    
    @category_grandchildren_default = []
    @product.category.siblings.each do |grandchild| 
      @category_grandchildren_default << grandchild  #表示している商品に紐付く孫カテゴリー
    end

    if @product.brand_id != nil
      @brand = @product.brand.name
    else
      @brand = ''
    end
  end

  def set_category
    #トップページに表示する商品のカテゴリー設定
    parents = (1..13).to_a
    parents.each do |parent|
      children = Category.where('ancestry LIKE(?)', "#{parent}/%")
      ids = []
      children.each do |child|
        ids << child[:id]
      end
      products = Product.where(category_id: ids).order("id DESC").limit(10)
      instance_variable_set("@category#{parent}", products)
    end
  end

  def set_brand
    #トップページに表示する商品のブランド設定
    #2440: シャネル 6142: ルイ ヴィトン 6758: シュプリーム 3802: ナイキ
    main_brand_ids = [2440, 6142, 6758, 3802]
    main_brand_ids.each do |brand|
      products = Product.where(brand_id: brand).order("id DESC").limit(10)
      instance_variable_set("@brand#{brand}", products)
    end
  end

  def get_category_children_new
      @category_children_new = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_size_new
    selected_grandchild = Category.find("#{params[:grandchild_id]}")
    if related_size_parent = selected_grandchild.sizes[0] 
      @sizes = related_size_parent.children 
    else
      selected_child = Category.find("#{params[:grandchild_id]}").parent 
      if related_size_parent = selected_child.sizes[0] 
        @sizes = related_size_parent.children 
      end
    end
  end

  def get_category_grandchildren_new
    @category_grandchildren_new = Category.find("#{params[:child_id]}").children
    return @category_grandchildren_new
  end

end

private
def product_params
  params.require(:product).permit(:name, :description, :category_id, :condition, :shipping_charge, :shipping_method, :ship_from, :shipping_days, :current_status, :payment_method, :price, :id, product_images_attributes:[ :image, :id, :_destroy ]).merge(seller_id: current_user.id)
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_items.html.haml
- products.each do |product|
  = link_to " " do
    .new-products__category__content__box
      = image_tag product.product_images.first.image.url, alt: '画像', class: 'new-products__category__content__box--image'
      %span.new-products__category__content__box--price
        =number_to_currency(product.price.to_s(:delimited), :unit => "￥")
      .new-products__category__content__box--information
        =product.name

app/views/products/_items_index.html.haml
- products.each do |product|
  = link_to product_path(product) do
    .new-products__category__content__box
      = image_tag product.product_images.first.image.url, alt: '画像', class: 'new-products__category__content__box--image'
      %span.new-products__category__content__box--price
        =number_to_currency(product.price.to_s(:delimited), :unit => "￥", :format => "%u%n", :precision => 0)
      .new-products__category__content__box--information
        =product.name

app/views/products/_items_show.html.haml
- products.each do |product|
  = link_to product_path(product) do
    .other-items__users__content__box
      = image_tag product.product_images.first.image.url, alt: '画像', class: 'other-items__users__content__box--image'
      .other-items__users__content__box--body
        .other-items__users__content__box--body--top
          =product.name
        %span.other-items__users__content__box--body--bottom
          .other-items__users__content__box--body--bottom--price
            =number_to_currency(product.price.to_s(:delimited), :unit => "￥")
          .other-items__users__content__box--body--bottom--like
            = fa_icon "heart-o",class: "icon"
            =product.like

app/views/products/new.html.haml
.product-container
  .product--header
    %h1
      =link_to ""
      = image_tag "top_page/header-mercari.svg", size: '193x49', alt:"mercari"  
  .product--main
    .product--main__body
      .product--main__body-head
        %h2
          商品の情報を入力
      .product--main__body__form
        = form_for @product do |f|
          .product--main__body__form--upload
            %h3.upload--header
              出品画像
              %span.form-require
                必須
            %p 最大10枚までアップロードできます
            .upload--container#preview_result
              %ul

              .upload--container--drop-box
                %p.upload--container--drop-box--text
                  ドラッグアンドドロップ
                  またはクリックしてファイルをアップロード
                = f.fields_for :product_images do |j|    
                  = j.label :image, multiple: true, class: "upload--container--drop-box--label"
                  = j.file_field :image, multiple: true, name: 'product_images[image][]', class: 'upload--container--drop-box--form', type: "file", onchange: "preview_file(this.id)"
                  = j.hidden_field :id, value: j.object.id
          .product--main__body-content
            .content-form
              %label
                %h3.sell--header
                  商品名
                  %span.form-require
                    必須
              = f.text_field :name, required: true, class: "name-form", placeholder: "商品名（40字まで）"
            .content-form
              %h3.sell--header
                商品の説明
                %span.form-require
                  必須
              = f.text_area :description, class: "textarea-form", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"

          .product--main__body-content
            %h3.content-form-title-gray
              商品の詳細
            .content-form-box
              .content-form__status-category
                = f.label 'カテゴリー', class: 'listing-default__label'
                %span.form-require 必須
                .select-wrap
                  .select-default
                    = f.select :category_id, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category-new'}
                    %i.fas.fa-chevron-down
              .content-form__status
                %label 
                  商品の状態
                  %span.form-require
                    必須
                .select-wrap
                  .select-default
                    = f.select :condition, options_for_select(Product.conditions.keys.map {|k| [I18n.t("enums.product.condition.#{k}"), k]}), {prompt: "---"}
                    %i.fas.fa-chevron-down

          .product--main__body-content
            %h3.content-form-title-gray
              配送について
            .content-form-box
              .content-form__status
                %label 
                  配送料の負担
                  %span.form-require
                    必須
                .select-wrap
                  .select-default 
                    = f.select :shipping_charge, options_for_select(Product.shipping_charges.keys.map {|k| [I18n.t("enums.product.shipping_charge.#{k}"), k]}), {prompt: "---"}
                    %i.fas.fa-chevron-down
              .content-form__status
                %label 
                  配送の方法
                  %span.form-require
                    必須
                .select-wrap
                  .select-default
                    = f.select :shipping_method, options_for_select(Product.shipping_methods.keys.map {|k| [I18n.t("enums.product.shipping_method.#{k}"), k]}), {prompt: "---"}
                    %i.fas.fa-chevron-down

              .content-form__status
                %label 
                  発送元の地域
                  %span.form-require
                    必須
                .select-wrap
                  .select-default
                    = f.collection_select :ship_from, Prefecture.all, :id, :name, {prompt: "--"}
                    %i.fas.fa-chevron-down
              .content-form__status
                %label 
                  発送までの日数
                  %span.form-require
                    必須
                .select-wrap
                  .select-default
                    = f.select :shipping_days, options_for_select(Product.shipping_days.keys.map {|k| [I18n.t("enums.product.shipping_days.#{k}"), k]}), {prompt: "---"}
                    %i.fas.fa-chevron-down
          .product--main__body-content
            %h3.content-form-title-gray
              販売価格(300〜9,999,999)
            .sell-form
              %ul.sell-form__status
                %li.content-form__status
                  %label
                    価格
                    %span.form-require
                      必須
                  .content-form__status__price-right
                    .select-wrap-right-price
                      %p
                        ¥
                    .select-default
                      = f.text_field :price, placeholder: "例）300", class: "price-form", id: "price_calc"
                %li.content-form__status
                  .content-form__status__fee-left
                    販売手数料(10%)
                  .content-form__status__fee-right
                    %p#output
                      ¥
                %li.content-form__status
                  .content-form__status__profit-left
                    販売利益
                  .content-form__status__profit-right
                    %p#output
                      ¥
                  
          .product--main__body-content--button
            .product--main__body-content--button-text
              %p 
                %a{ :href => "https://www.mercari.com/jp/help_center/getting_started/prohibited_items/" }禁止されている出品
                、
                %a{ :href => "https://www.mercari.com/jp/help_center/getting_started/prohibited_conduct/" }行為
                を必ずご確認ください。
              %p 
                またブランド品でシリアルナンバー等がある場合はご記載ください。
                %a{ :href => "https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/" }偽ブランドの販売
                は犯罪であり処罰される可能性があります。
              %p 
                また、出品をもちまして
                %a{ :href => "https://www.mercari.com/jp/seller_terms/" }加盟店規約
                に同意したことになります。
            = f.submit "出品する", class: 'product--main__body-content--button-next'
            = link_to "もどる", products_path, class: 'product--main__body-content--button-back'
  .product--footer
    .product--footer__view
      %nav
      %li
        %a{ :href => "https://www.mercari.com/jp/privacy/" }プライバシーポリシー
      %li
        %a{ :href => "https://www.mercari.com/jp/privacy/" }メルカリ利用規約
      %li
        %a{ :href => "https://www.mercari.com/jp/tokutei/" }特定商取引に関する表記
    .product--footer__view__logo
      =link_to ""
      = image_tag "registrations_page/logo-gray.svg", size: '80x65', alt:"mercari" do end
    %p © 2019 Mercari

app/views/products/show.html.haml
.item
  .item__name
    =@product.name
  .item__content
    .item__content__photo
      %ul.main-window
        - @product_images.each do |product_image|
          %li
            = image_tag product_image.image, alt: "画像", size: "300x300"

      %ul.sub-window
        - @product_images.each do |product_image|
          %li
            = image_tag product_image.image, alt: "画像", size: "60x60"

    %table.item__content__detail
      %tr
        %th 出品者
        %td
          = @product.seller.nickname
          .icon-list
            -if Evaluation.find_by(user_id: @product[:seller_id]).present?
              .icon.good
                = @product.seller.evaluation.good
              .icon.normal
                = @product.seller.evaluation.normal
              .icon.bad
                = @product.seller.evaluation.bad
            - else
              .icon.good
                = "  0"
              .icon.normal
                = "  0"
              .icon.bad
                = "  0"
      %tr
        %th カテゴリー
        %td
          = link_to " " do
            .category
              = @product.category.root.name
          - if @product.category.name == 'オートバイ車体'
            = link_to " " do
              .category
                = @product.category.name
          - else
            = link_to " " do
              .category
                = @product.category.parent.name
            = link_to " " do
              .category
                = @product.category.name

      %tr
        %th ブランド
        %td 
          - if @product.brand_id.present?
            = link_to " " do
              = @product.brand.name

      -if @product.size_id.present?
        %tr
          %th 商品のサイズ
          %td 
            = @product.size.name
              
      %tr
        %th 商品の状態
        %td 
          = @condition
      %tr
        %th 配送料の負担
        %td 
          = @shipping_charge
      %tr
        %th 配送の方法
        %td 
          = @shipping_method
      %tr
        %th 配送元地域
        %td
          = link_to " " do
            = @ship_from
      %tr
        %th 配送日の目安
        %td 
          = @shipping_days
            

            
          
  .item__amount
    .item__amount--price
      = "¥ #{@product.price}"
    .item__amount--tax
      （税込）
    .item__amount--shipping-fee
      送料込み
  -if @product.buyer_id.present?
    .item__sell-btn
      売り切れました
  -else
    .item__buy-btn
      = link_to "購入画面に進む", purchases_path(product: @product)
   
  .item__description
    = @product.description

  .item__buttons
    .item__buttons--left
      .item__buttons--left--like
        = fa_icon "heart-o",class: "menu__icon"
        いいね！
      .item__buttons--left--report
        = fa_icon "flag-o",class: "menu__icon"
        不適切な商品の報告
    .item__buttons--right
      = fa_icon "lock",class: "menu__icon"
      あんしん・あんぜんへの取り組み

.comment
  .comment__list
  .comment__box
    = form_for [@product, @comment], html: { id: 'new-comment' } do |f|
      %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      = f.text_area :content, class: "input"
      = f.submit "コメントする", class: "button"
.nav
  .nav--prev
    PREV
  .nav--next
    NEXT

.social-media
  .social-media__box
    .social-media__box--facebook
    .social-media__box--twitter
    .social-media__box--pinterest

.other-items
  .other-items__users
    .other-items__users__header
      = link_to " " do
        = "#{@user.nickname}さんのその他の出品"
    .other-items__users__content
      = render 'items_show', products: @products_related_user
  .other-items__related
    .other-items__related__header
      = link_to " " do
        -if @product.brand_id != nil
          = "#{@product.brand.name}の#{@product.category.name}その他の出品"
        -else
          = "#{@product.category.name}その他の出品"
    .other-items__related__content
      = render 'items_show', products: @products_related_category
.bread-crumbs__bottom
  %ul
    %li
      = link_to root_path do
        メルカリ
    %li
      = @product.name
        

app/views/products/show_mine.html.haml
.item
  .item__name
    メルカリサンプル
  .item__content
    .item__content__photo
      %ul.main-window
        - @product_images.each do |product_image|
          %li
            = image_tag product_image.image, alt: "画像", size: "300x300"
        -#仮置き画像
        %li
          = image_tag "mypage/mypage-icon-mercari.png", alt: "画像", size: "300x300"
        %li
          = image_tag "mypage/mypage-icon-mercari.png", alt: "画像", size: "300x300"
        %li
          = image_tag "mypage/mypage-icon-mercari.png", alt: "画像", size: "300x300"
        %li
          = image_tag "mypage/mypage-icon-mercari.png", alt: "画像", size: "300x300"
        %li
          = image_tag "mypage/mypage-icon-mercari.png", alt: "画像", size: "300x300"

      %ul.sub-window
        - @product_images.each do |product_image|
          %li
            = image_tag product_image.image, alt: "画像", size: "60x60"
        -#仮置き画像
        %li
          = image_tag "mypage/mypage-icon-mercari.png", alt: "画像", size: "60x60"
        %li
          = image_tag "mypage/mypage-icon-mercari.png", alt: "画像", size: "60x60"
        %li
          = image_tag "mypage/mypage-icon-mercari.png", alt: "画像", size: "60x60"
        %li
          = image_tag "mypage/mypage-icon-mercari.png", alt: "画像", size: "60x60"
        %li
          = image_tag "mypage/mypage-icon-mercari.png", alt: "画像", size: "60x60"

    %table.item__content__detail
      %tr
        %th 出品者
        %td
          = @product.seller.nickname
          .icon-list
            .icon.good
              = @product.seller.evaluation.good
            .icon.normal
              = @product.seller.evaluation.normal
            .icon.bad
              = @product.seller.evaluation.bad
      %tr
        %th カテゴリー
        %td
          = link_to " " do
            .category
              = @product.category.root.name
          = link_to " " do
            .category
              = @product.category.parent.name
          = link_to " " do
            .category
              = @product.category.name
      %tr
        %th ブランド
        %td 
          - if @product.brand_id.present?
            = link_to " " do
              = @product.brand.name

      -if @product.size_id.present?
        %tr
          %th 商品のサイズ
          %td 
            = @product.size.name
              
      %tr
        %th 商品の状態
        %td 
          = @condition
      %tr
        %th 配送料の負担
        %td 
          = @shipping_charge
      %tr
        %th 配送の方法
        %td 
          = @shipping_method
      %tr
        %th 配送元地域
        %td
          = link_to " " do
            = @ship_from
      %tr
        %th 配送日の目安
        %td 
          = @shipping_days
            

            
          
  .item__amount
    .item__amount--price
      = number_to_currency(@price, :unit => "￥", :precision => 0)
    .item__amount--tax
      （税込）
    .item__amount--shipping-fee
      送料込み
  -# .item__buy-btn
  -#   購入画面に進む
  .item__description
    = @product.description

  .item__buttons
    .item__buttons--left
      .item__buttons--left--like
        = fa_icon "heart-o",class: "menu__icon"
        いいね！
      .item__buttons--left--report
        = fa_icon "flag-o",class: "menu__icon"
        不適切な商品の報告
    .item__buttons--right
      = fa_icon "lock",class: "menu__icon"
      あんしん・あんぜんへの取り組み

.buttons
  =link_to edit_product_path(@product) do
    .buttons--red
      商品の編集
  %p or
  =link_to "" do
    .buttons--gray
      出品を一旦停止する
  =link_to "" do
    .buttons--gray
      この商品を削除する

.comment
  .comment__list
  .comment__box
    = form_for [@product, @comment], html: { id: 'new-comment' } do |f|
      %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      = f.text_area :content, class: "input"
      = f.submit "コメントする", class: "button"

app/views/products/show_my_product.html.haml
-if @product.current_status_i18n == '出品中'
  - breadcrumb :selling_item
  = render "layouts/breadcrumbs"

-elsif @product.current_status_i18n == '取引中'
  - breadcrumb :trading_item
  = render "layouts/breadcrumbs"

-else
  - breadcrumb :completed_item
  = render "layouts/breadcrumbs"

.item
  .item__name
    = @product.name
  .item__content
    .item__content__photo
      %ul.main-window
        - @product_images.each do |product_image|
          %li
            = image_tag product_image.image, alt: "画像", size: "300x300"

      %ul.sub-window
        - @product_images.each do |product_image|
          %li
            = image_tag product_image.image, alt: "画像", size: "60x60"

    %table.item__content__detail
      %tr
        %th 出品者
        %td
          = @product.seller.nickname
          - if @product.seller.evaluation.present?
            .icon-list
              .icon.good
                = @product.seller.evaluation.good
              .icon.normal
                = @product.seller.evaluation.normal
              .icon.bad
                = @product.seller.evaluation.bad
      %tr
        %th カテゴリー
        %td
          = link_to " " do
            .category
              = @product.category.root.name
          - if (@product.category.name == 'オートバイ車体') || ( (@product.category.name == 'その他') && (@product.category.children?) )
            = link_to " " do
              .category
                = @product.category.name
          - else
            = link_to " " do
              .category
                = @product.category.parent.name
            = link_to " " do
              .category
                = @product.category.name
      %tr
        %th ブランド
        %td 
          - if @product.brand_id.present?
            = link_to " " do
              = @product.brand.name

      -if @product.size_id.present?
        %tr
          %th 商品のサイズ
          %td 
            = @product.size.name
              
      %tr
        %th 商品の状態
        %td 
          = @condition
      %tr
        %th 配送料の負担
        %td 
          = @shipping_charge
      %tr
        %th 配送の方法
        %td 
          = @shipping_method
      %tr
        %th 配送元地域
        %td
          = link_to " " do
            = @ship_from
      %tr
        %th 配送日の目安
        %td 
          = @shipping_days
            

            
          
  .item__amount
    .item__amount--price
      = number_to_currency(@price, :unit => "￥",:format => "%u%n", :precision => 0)
    .item__amount--tax
      （税込）
    .item__amount--shipping-fee
      送料込み
  .item__description
    = @product.description

  .item__buttons
    .item__buttons--left
      .item__buttons--left--like
        = fa_icon "heart-o",class: "menu__icon"
        いいね！
      .item__buttons--left--report
        = fa_icon "flag-o",class: "menu__icon"
        不適切な商品の報告
    .item__buttons--right
      = fa_icon "lock",class: "menu__icon"
      あんしん・あんぜんへの取り組み

.buttons
  =link_to edit_product_path(@product) do
    .buttons--red
      商品の編集
  %p or
  =link_to "" do
    .buttons--gray
      出品を一旦停止する
  =link_to product_path, method: :delete do
    .buttons--gray
      この商品を削除する

.comment
  .comment__list
  .comment__box
    = form_for [@product, @comment], html: { id: 'new-comment' } do |f|
      %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      = f.text_area :content, class: "input"
      = f.submit "コメントする", class: "button"